### ISSUE TITLE
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,2)  and requested shape (3,2)

### ISSUE THREAD

**Issue by lanyao-wang** [JeremyOng96/A-Hybrid-Method-for-Pavement-Crack-Width-Measurement#2]
May I ask how to solve this problem? 
Thanks a lot!!

**Comment by JeremyOng96** [comment]
Hi, it has been awhile since I reviewed this code. Can you just take a screenshot so that I can reproduce the error?

**Comment by lanyao-wang** [comment]
![image](https://user-images.githubusercontent.com/57058290/231633329-2c4b6a04-f653-499a-8111-d25f3099b042.png)

**Comment by JeremyOng96** [comment]
Hi,

This might be a problem with your data. The input assumes binary data where the image shape should be (h,w). Let me know if this works.

**Comment by lanyao-wang** [comment]
Hi,
Since I am a newbie, could you please tell me which part of the code should I modify?
Is it line 484?

**Comment by JeremyOng96** [comment]
Line 484 could be the problem. But I suggest you check the input size of your image. image.shape will give you the shape of your image. Let's say you are working on a 256 by 256 image, then it should be (256,256). If your image is (256,256,1) then I think image.squeeze() should work. Let me know

**Comment by lanyao-wang** [comment]
I just tried the image.shape method and got my image as (547, 820, 3).
![image](https://user-images.githubusercontent.com/57058290/231636861-89fdc16c-b535-4ac3-ad0b-8917736e360c.png)

Should I use binarize method to convert RGB image as input？？

**Comment by JeremyOng96** [comment]
I see that your image has 3 channels (RGB format). This is likely due to the use of cv2.imread method. If you think that your image is truly binary, then a simple cv2.imread(img,cv2.IMREAD_UNCHANGED) should do the trick. If not, a simple work around will be image[:,:,0]. Since your image is already black and white, means the 3 channels are just duplicates, then obtaining one channel should be the same.

**Comment by lanyao-wang** [comment]
By  cv2.imread(img,cv2.IMREAD_UNCHANGED) method I got (547,820).
Is this input correct?

**Comment by JeremyOng96** [comment]
This should be right. However, you are working on a large image and the processing time will be quite slow. I suggest you work on smaller images to test out the algorithm first.

**Comment by lanyao-wang** [comment]
Thanks! it works!
But if use the folder form, the shape is wrong. I tried with a single image and it was correct.
![image](https://user-images.githubusercontent.com/57058290/231643162-0fd7873d-9a3e-42e8-822c-c38665e4139e.png)

**Comment by JeremyOng96** [comment]
I am glad that it is working now on your side, if you find our work useful to your project, please cite us.

I see that your images are saved in png format, but your code searches for *jpg. These are different files, and likely cv2 cannot read these images. I think you should try changing *jpg to *png. Let me know if this works.

**Comment by lanyao-wang** [comment]
When I test with a picture in jpg format, the previous problem occurs. There will be no errors when using images in png format, so may only be able to use images in png format for testing.
