### ISSUE TITLE
which file to run

### ISSUE THREAD

**Issue by bulingyuu** [JeremyOng96/A-Hybrid-Method-for-Pavement-Crack-Width-Measurement#3]
May I ask how to modify the image path, because I see that there are three files with paths. And what is the order in which the files are run

**Comment by JeremyOng96** [comment]
Hi, it's been awhile since I have reviewed this code, but modifying just the measurement_methods file should be good enough. Let me know if it works.

**Comment by bulingyuu** [comment]
thanks for your answer. I'm a bit confused since I found folder_path  in measurement_methods,intersection_remover and DSE_prune.

**Comment by bulingyuu** [comment]
YES.My name is Li Yiyi, and I am a graduate student majoring in communication at Chongqing University of Technology. I'm currently doing research on detecting cracks. I saw your paper through github and thought it was very well written and inspired me a lot. But I'm new to image processing, and it may be a bit difficult to read the code.

**Comment by JeremyOng96** [comment]
你好，我是駿輝。如果有啥事，你可以問問我。幫得助你是我榮幸

**Comment by bulingyuu** [comment]
谢谢老师，学生感激不尽。可以问一下面这段代码的作用是什么嘛，我用文件中自带的crack500_140_labeled.png进行测试会报错list index out of range
    # padding 
    padded_mask = [38]
    for mask in mask_files:
        pad_mask = np.pad(mask,((2,2),(2,2)),"constant")
        padded_mask.append(pad_mask)
    
    test_img = padded_mask[38]

**Comment by bulingyuu** [comment]
谢谢老师，学生感激不尽。可以问一下面这段代码的作用是什么嘛，我用文件中自带的crack500_140_labeled.png进行测试会报错list index out of range
    # padding 
    padded_mask = [38]
    for mask in mask_files:
        pad_mask = np.pad(mask,((2,2),(2,2)),"constant")
        padded_mask.append(pad_mask)
    
    test_img = padded_mask[38]

**Comment by JeremyOng96** [comment]
我覺得很有可能你的文件夾里只有一張照片，所以報錯了。

**Comment by bulingyuu** [comment]
对不起老师我不知道该如何修改 我需要放多少个图片呢

**Comment by JeremyOng96** [comment]
只需要一张图就行
